import { Inter } from "next/font/google";
import Head from "next/head";
import Link from "next/link";
import { TfiSearch } from "react-icons/tfi";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ title, allData }: any) {
  return (
    <>
      <Head>
        <title>Event Bliss Hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/mylogo.png" />
      </Head>
      <main className="home">
        <img
          src="https://images.pexels.com/photos/2747448/pexels-photo-2747448.jpeg"
          alt=""
        />

        <div className="home-details">
          <div className="intro">
            <h1> event bliss hub</h1>
            <p>Your Event finder</p>
          </div>
          <div className="search">
            <input type="text" placeholder="Enter Event or Country" />
            <TfiSearch className="iconic" />
          </div>
          <div className="actions">
            <Link className="link" href="/">
              Home
            </Link>
            <Link className="link" href="/Events">
              Events
            </Link>
            <Link className="link" href="/about">
              About
            </Link>
            <Link className="link" href="/contact">
              Contact
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
